[package]
name = "multiqueue"
version = "0.1.0"
edition = "2024"

[dependencies]
indoc = "2.0.6"
sqlx = { version = "0.8.5", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.44.2", features = ["full"] }
